table uniprotDecoration
"BED12 definition for Uniprot decorations, derived from decoration.as"
    (
    string chrom;      "Chromosome (or contig, scaffold, etc.)"
    uint   chromStart; "Start position in chromosome"
    uint   chromEnd;   "End position in chromosome"
    string name;       "Name of item"
    uint   score;      "Score from 0-1000"
    char[1] strand;    "+ or -"
    uint thickStart;   "Start of where display should be thick (start codon)"
    uint thickEnd;     "End of where display should be thick (stop codon)"
    uint color;        "Primary RGB color for the decoration"
    int blockCount;    "Number of blocks"
    int[blockCount] blockSizes; "Comma separated list of block sizes"
    int[blockCount] chromStarts; "Start positions relative to chromStart"
    string decoratedItem; "Identity of the decorated item in chr:start-end:item_name format"
    string style;      "Draw style for the decoration (e.g. block, glyph)"
    string fillColor;  "Secondary color to use for filling decoration, blocks, supports RGBA"
    string glyph;  "The glyph to draw in glyph mode; ignored for other styles"

    string annotType;   "The type of the annotation: 'feature' or 'disruption'"
    string dataSet;     "'SwissProt' (manual annotation) or 'TrEMBL' (automated annotation)"
    string uniprotAcc;  "UniProt accession"
    string transCategory; "transcript category for UniProt: 'canonical', 'canonical_diff_version', 'noncanonical'"
    string srcTransId;  "source transcript id; this is the one annotated by UniProt"
    string mappedTransId;  "transcript id of the transcript to which the annotation is mapped; for cross-species, this is the the target species"
    string featStatus;   "For features, either 'complete' or 'disrupted', for disruptions 'insert', 'del_5p' for 5' delete, 'del_3p' for 3' deletion, or ''del_int' for internal deletions"
    string category;  "Feature category symbolic name"
    string categoryName;  "Feature category descriptive name"
    lstring description; "Description of annotation or disruption"
    string shortFeatType;  "Short feature type, often groups multiple feature types"
    string featType;       "Type of feature"
    string shortName;  "Short descriptive name of feature "
    lstring longName;   "Descriptive name of feature"
    lstring comment;   "Comment"
    lstring disease;   "Disease for disease-related variants"
    )
