
* Alignment of protein to transcripts

Converting protein to transcript alignments to CDS to transcript alignment, by
multiplying the AA coordinates by three handles spliced codons once mapped to
genome.

Initially approach was to align proteins to both canonical and non-canonical
transcripts and pick the best alignments.  However, there were a number of
discrepancies in the non-canonical transcript alignments.  This was change to
only align to canonical and then project these alignments to the non-canonical
transcripts, which resulted in a significant improvement.

Alignments are done to canonical transcript where the UTR is hard-masked to
prevent alignment into UTR.  Projection to non-canonical transcripts have
UTR projection trimmed.

Both BLAT protein to DNA and TBLASTN were tried to align the UniProt
proteins.  When aligning only to the canonical transcript, the difference
were negligible. Could probably avoid a lot of the BLAT alignments by
check if the transcript version was the same and just construct it.

An optimization would be to avoid alignments to the canonical mRNA
when there is an exact match.

* Cross-species projection of UniProt/SwissProt annotations
Native TrEMBL annotations at available for many species and these can be
mapped to the genome using this pipeline. SwissProt annotations, when
available, are more extensive and can be mapped using cross-species genomic
alignments

* InterProScan
InterProScan is run directly on proteins generated from the annotations, thus
an alignment step is unnecessary.

* Cross-species comparison
Projection (TransMap) alignments of SwissProt from a reference genome to the
target genome can find deleted and modified domains; however the do not
identify novel domains.  Comparison with InterProScan may fine novel insertions.

** Comparison is done by:
 - Use the pair source and target RNAs used for the mapping
 - use a selective subset of annotations
 - disallow overlapping annotations in one set
 - Mapped SwissProt annotations are more comprehensive than native or mapped
   TrEMBL or InterProScan, but could also include native TrEMBL at some point.
   However, the xspecies assembly needs to be in Ensembl or have to map
   between assembly versions.
   
** Details:
*** uniprot to xspecies mappings
- uniprotMetaTsv
- annot2GenomePsl (xspecies)
- annot2GenomeRefTsv (xspecies)
- xspeciesTrans2TransPsl
*** intropro target annotation to mRNA alignments
- interproAnnot.tsv
- interproAnnot2Trans.psl ??? really needed?? 
- interproAnnot2Genome.psl
- interproAnnot2GenomeRef.tsv
  
*** Logical ling the mappings are
srcAnnot-srcTrans -> 
srcTrans-targetGenome <-> targetGenome-targetTrans
<- targetTrans-targetAnnot


*** want to report
**** if mapped is disrupted or deleted
**** if mapped and interpro conflict or significant disagrees in similarity and bounds
**** if interpro is is not in mapped

*** algorithms:
**** filter for annotations of interest
**** build a merged list of annotations
initialize with list of mapped or deleted uniprots
**** scan interpro
update list

